### ISSUE TITLE
聊天记录显示不了

### ISSUE THREAD

**Issue by 1182469644** [zhongmax/srent#12]
为啥聊天框这里聊天记录显示不了，是需要用到腾讯云开发吗，写到了云数据库里？

**Comment by 1182469644** [comment]
![1707105053792](https://github.com/zhongmax/srent/assets/128795975/a44598aa-4729-416c-842a-cdd8dc206802)

**Comment by zhongmax** [comment]
用的微信小程序的数据库
文档：https://developers.weixin.qq.com/miniprogram/dev/wxcloud/basis/capabilities.html#%E6%95%B0%E6%8D%AE%E5%BA%93
