### ISSUE TITLE
大佬，node多少版本，后台依赖没安装上

### ISSUE THREAD

**Issue by pzl456** [zhongmax/srent#13]

**Comment by zhongmax** [comment]
贴一下错误

**Comment by zhongmax** [comment]
这个版本可以哈，我刚才试过了
```shell
node --version
v14.21.3
```

**Comment by pzl456** [comment]
谢谢大佬回复，我之前用node10，16，18不行，切换成node14可以了


| |
潘子龙
|
|
18731139782
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年2月17日 18:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [zhongmax/srent] 大佬，node多少版本，后台依赖没安装上 (Issue #13) |

这个版本可以哈，我刚才试过了

node --version
v14.21.3

**Comment by 30warriors30** [comment]
我好像不行
