### ISSUE TITLE
七牛云

### ISSUE THREAD

**Issue by 30warriors30** [zhongmax/srent#17]
qiniu.csmaxwell.xyz这是什么？
![image](https://github.com/zhongmax/srent/assets/98330762/2abd51a4-5d5e-4167-b077-a3ae76678c0d)
![image](https://github.com/zhongmax/srent/assets/98330762/1b91ee5f-bd00-4f7c-8af1-76e4192d8e2f)

**Comment by zhongmax** [comment]
这是七牛oss的域名，这个桶我已经关了

**Comment by 30warriors30** [comment]
如果是用自己申请的，七牛云中是不是还需要上传所需的照片

**Comment by 30warriors30** [comment]
我还想问一下这个的后端入口是哪里

**Comment by zhongmax** [comment]
> 如果是用自己申请的，七牛云中是不是还需要上传所需的照片

是的

**Comment by zhongmax** [comment]
> 我还想问一下这个的后端入口是哪里

![image](https://github.com/zhongmax/srent/assets/20065316/62e151b6-2302-4ecb-a446-c7d4af46e1db)

**Comment by zhongmax** [comment]
入口是srent-wx-api这个module

**Comment by 30warriors30** [comment]
locahost：8080点进去还像是错误页面

**Comment by zhongmax** [comment]
> locahost：8080点进去还像是错误页面

你后端启动了吗

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/e80d04d9-8873-4099-a6b0-a27eb0c5fb53)
这个怎么解决

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/8dce9e97-a354-4780-baca-bababbfbb6f5)

**Comment by zhongmax** [comment]
你贴错，能贴完嘛?

**Comment by 30warriors30** [comment]
这个解决了

**Comment by 30warriors30** [comment]
大佬能帮我远程调式一下吗？

**Comment by zhongmax** [comment]
> 大佬能帮我远程调式一下吗？

还有问题？

**Comment by zhongmax** [comment]
你直接在这说吧

**Comment by 30warriors30** [comment]
这些程序调用有顺序吗
![image](https://github.com/zhongmax/srent/assets/98330762/934477ed-bc0e-42e0-907a-bf871f237f55)

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/5546bb87-f80d-4083-bb9a-014815470768)
小程序这边一部分内容没有出现‘

**Comment by 30warriors30** [comment]
后端登录时出现这种情况

**Comment by zhongmax** [comment]
> ![image](https://private-user-images.githubusercontent.com/98330762/342264480-5546bb87-f80d-4083-bb9a-014815470768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTk1MzksIm5iZiI6MTcxOTIxOTIzOSwicGF0aCI6Ii85ODMzMDc2Mi8zNDIyNjQ0ODAtNTU0NmJiODctZjgwZC00MDgzLWJiOWEtMDE0ODE1NDcwNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDA4NTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZTBiODVlZTE4OGI4YTcxYzdhMGFkYzNiZjNiZDc1YzRjZTI5NTUzYzhiMDRlNTJiMjQwM2I4YmQyNmIxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sez0O5m_m8lSqQ5R44WJ55WNjiNtmVsYRrN4Tw-DSSU) 小程序这边一部分内容没有出现‘

来个邮箱，我把图片发给你

**Comment by 30warriors30** [comment]
1464292485@qq.com

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/6c9b487a-60e5-470e-abf9-4ea8c4fe6e60)
api.js中修改哪一部分

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/c7f1c80e-521f-4f79-a8e3-b20fbe0a9e23)
后端登录出现这种情况怎么办

**Comment by zhongmax** [comment]
有日志的，你自己看看吧

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/b405028e-5b55-4888-9848-0240ad9d1d56)
管理员不是这个账户吗

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/b405028e-5b55-4888-9848-0240ad9d1d56)
![Uploading image.png…]()
管理员不是这个账户吗

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/b36cf10d-573f-4b39-8d6c-4eb80604e850)
大佬现在我这边是不是只是七牛云的问题了。

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/b405028e-5b55-4888-9848-0240ad9d1d56)
管理员不是这个账户吗

**Comment by zhongmax** [comment]
你自己研究吧，拿数据库加密的密码来登录...

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/c4e4fb71-3290-4c36-90ec-0ed7d68865d7)
我用的是数据这个复制过去

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/14e5f132-5411-4e9f-8d5c-30fc372d603c)
大佬，我现在这样是不是只是七牛云有问题

**Comment by 30warriors30** [comment]
![image](https://github.com/zhongmax/srent/assets/98330762/a2cfad6a-8852-466a-87ad-694c002a8945)
大佬我就是用的数据的管理员为什么会后端登录失败呢

**Comment by 30warriors30** [comment]
大佬最后一个问题了，是真的不会，&nbsp;


几度雨停
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhongmax/srent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 下午5:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhongmax/srent] 七牛云 (Issue #17)





 
你自己研究吧，拿数据库加密的密码来登录...

**Comment by 30warriors30** [comment]
后端管理员的密码是多少？

**Comment by zhongmax** [comment]
你真的有学过web开发吗，拿数据库加密的密码来登录，逆天
![image](https://github.com/zhongmax/srent/assets/20065316/9d33eed4-f6a2-4506-a228-4f8d1ce76c51)
