### ISSUE TITLE
可以升级成mybatis-plus

### ISSUE THREAD

**Issue by Mr-Qiuqi** [zhongmax/srent#2]
毕she需要过来看了哈，功能还不错~
上传文件： fastDFS可以考虑哈
热搜：es
登录配置个：redis
可以升级成mybatis-plus， 看着以前老的example的那些泪两行。
实现类最好用inteface ，然后加个后台admin模块,(开源  itmall也是有的）
vue + element ui ，一整套就出来了

**Comment by zhongmax** [comment]
还在学习中，感谢提出意见~
