### ISSUE TITLE
srent admin 后台登录失败，报502错误

### ISSUE THREAD

**Issue by lovingman** [zhongmax/srent#4]
系统内部错误，请联系管理员维护

**Comment by zhongmax** [comment]
你好，刚才测试了一下，发现maven的hibernate-validator版本更新，不知道是否为这个原因，我这边测试，管理后台是可以正常登陆的，srent-admin是Vue项目，使用VS Code或者其他编辑器打开，在终端srent-admin路径下输入cnpm install，之后再cnpm run dev

**Comment by zhongmax** [comment]
已经将依赖更换，可以重新clone或者pull下来，再试试

**Comment by lovingman** [comment]
谢谢，其实还是没有解决，后台管理是没有用户密码是没有加密的吧。

**Comment by wdx6** [comment]
我也有这个问题

**Comment by 30warriors30** [comment]
请问大佬最后怎么登进后端的
