### ISSUE TITLE
{"errno":605,"errmsg":"认证失败"}

### ISSUE THREAD

**Issue by try-maker** [zhongmax/srent#7]
![image](https://user-images.githubusercontent.com/53518029/113173638-2c31e700-927c-11eb-9703-ff7eb6c68446.png)
不知道为什么一直认证失败

**Comment by zhongmax** [comment]
大概知道是什么问题了，没有更新数据库文件导致的，现在在加数据库的表和记录-_-|!

**Comment by try-maker** [comment]
我知道数据表里面没有数据，我加了相关的呀







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月1日(星期四) 上午10:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhongmax/srent] {&quot;errno&quot;:605,&quot;errmsg&quot;:&quot;认证失败&quot;} (#7)





 
大概知道是什么问题了，没有更新数据库文件导致的，现在在加数据库的表和记录-_-|!

**Comment by try-maker** [comment]
你好，作者。您刚才说的是少表和数据这个我加了，加了以后报的哪个错误

**Comment by zhongmax** [comment]
少了srent_role和srent_permission表

**Comment by try-maker** [comment]
哦，这个是没有

**Comment by zhongmax** [comment]
![image](https://user-images.githubusercontent.com/20065316/113237734-fc193100-92d9-11eb-81d7-c905e4a21943.png)

**Comment by try-maker** [comment]
🆗，我按照这个建表试试

**Comment by zhongmax** [comment]
shiro在登录的时候，会通过这个用户ID去查找role_list已经权限列表，因为没有srent_admin没有role_list这个字段，异常被catch，所以没有报错

**Comment by zhongmax** [comment]
我等会重新push一下sql

**Comment by try-maker** [comment]
ok, 感谢作者，问题已解决，
另外，开源不易，能否请作者喝杯咖啡。发个微信码到我邮箱
![image](https://user-images.githubusercontent.com/53518029/113239555-8747f600-92dd-11eb-9638-0c97f36654e3.png)

**Comment by zhongmax** [comment]
😂   不用，这个教程其实也是我从litemall那里抄过来，自己修修改改，跑起来的，还有一个项目 [mall](https://github.com/macrozheng/mall) 也可以学习一下，文档写的挺不错的

**Comment by try-maker** [comment]
这个mall商城我知道的，时不时看的。还是感谢啊



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhongmax/srent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月1日(星期四) 中午11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhongmax/srent] {"errno":605,"errmsg":"认证失败"} (#7)





 
�9�8   不用，这个教程其实也是我从litemall那里抄过来，自己修修改改，跑起来的，还有一个项目 mall 也可以学习一下，文档写的挺不错的

**Comment by try-maker** [comment]
发自我的iPhone
