### ISSUE TITLE
关于图片存储，显示的

### ISSUE THREAD

**Issue by try-maker** [zhongmax/srent#8]
我看项目中没有实现这个功能，还有就是七牛云配置除了下面的配置，其他的地方还有？
![image](https://user-images.githubusercontent.com/53518029/113243983-a72fe780-92e6-11eb-973f-4683baf314f1.png)
![image](https://user-images.githubusercontent.com/53518029/113244021-c7f83d00-92e6-11eb-8fbf-eea91a67ce7e.png)
![image](https://user-images.githubusercontent.com/53518029/113244168-0e4d9c00-92e7-11eb-935a-cf7b0e0a95d1.png)
![image](https://user-images.githubusercontent.com/53518029/113244201-1c9bb800-92e7-11eb-82a5-f983e3150c73.png)
![image](https://user-images.githubusercontent.com/53518029/113244287-48b73900-92e7-11eb-8e3f-6824963b07c2.png)

**Comment by zhongmax** [comment]
管理后台是后面匆匆加的，有些功能没做，具体的代码，可能要去看看litemall的代码
关于图片，七牛图床过期了，需要把图片链接前缀换成 http://maxw.oss-cn-shenzhen.aliyuncs.com
e.g. https://maxw.oss-cn-shenzhen.aliyuncs.com/banner3_1.jpg
